{% set name = "pointpats" %}
{% set version = "2.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pointpats-{{ version }}.tar.gz
  sha256: 1eedb30a17e59746ed9ac68283f419dee5a07c17cd53ed2bc2dadba2b77973ff

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.10
    - setuptools >=61.0
    - setuptools-scm >=6.2
  run:
    - libpysal >=4.8.0
    - matplotlib-base >=3.6
    - numpy >=1.24
    - pandas
    - python >=3.10
    - scipy >=1.10
    - shapely >=2.0
    - geopandas >0.12

test:
  imports:
    - pointpats
  # conda-forge does not have an opencv-contrib-python package yet
  # and it looks like an optional dependency here.
  # See https://github.com/pysal/pointpats/pull/82
  # commands:
  #   - pip check
  # requires:
  #   - pip

about:
  home: http://pysal.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Statistical analysis of planar point patterns.

  description: |
    This pointpats package is intended to support the statistical analysis
    of planar point patterns.
  doc_url: https://pointpats.readthedocs.io/en/latest/
  dev_url: https://github.com/pysal/pointpats

extra:
  recipe-maintainers:
    - weikang9009
    - slumnitz
    - martinfleis
    - knaaptime
    - jGaboardi
