{% set name = "pointpats" %}
{% set version = "2.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: dd210a01f634895d8272f89829613333b4158e9705310fa768ae6862b5737eb6

build:
  noarch: python
  number: 1
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - python >=3
    - pip
  run:
    - python >=3.4
    - scipy >=0.11
    - numpy >=1.3
    - pandas
    - matplotlib-base
    - libpysal >=4.0.0

test:
  imports:
    - pointpats

about:
  home: http://pysal.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: 'Statistical analysis of planar point patterns.'

  description: |
    This pointpats package is intended to support the statistical analysis
    of planar point patterns.
  doc_url: https://pointpats.readthedocs.io/en/latest/
  dev_url: https://github.com/pysal/pointpats

extra:
  recipe-maintainers:
    - weikang9009
    - slumnitz
