travis:
  secure:
    BINSTAR_TOKEN: aBwMpV438Y2VV2fhSvdr9GISDNHTvixqZmrDkupQ0s1M2UfxFRtQmHXpAXV6NcjXTI3J3n7tDTET7kpnSJ1lrCwUEf2iG/xsn5soPkdKwYtontwdyHWDyC43xqLeAR2s5AlgfxaDi6VQK7/tJTviJ44O5k4OQnDgfFEw+Hgncko2r89m6tvir3nI7ZokTd3B+JS8AH7Ewq4Ohr2DvoQQgwRRCrgpMz9bP2VXbVkKlYBtxdrAp2Z8CpzvmOHu/LyQR+hsSHYtyO1P5olqRR+Y9SjFekYqvRrlZn+lZ0THr2qJKDvsJAqtyKn/McBqpBbkohmPzWywQwKwk1EA5W2ESTU/GQGvpdyb8hF8GbKMEc7twvtGk5FCs2ffTlIcSPM+ZXiCCfk/KiX6v0Ra2+cn6kBbw34OQTjthdXHhNlV0ehSPMuGeRX+7cb8VJChIYGcnvch3dgy/AZ5jf+baP7frBUh+HQU+OWzVG+dzl8HrEEeNuifM5ESG1eL/1G2QmKS8YuYWs8V4+NQEl05Pbj0UGtW/i/AR7p4WRZ9nqOVVbEYrQrxl9wYBPadWo95JFdOfXXXwX8v6a8kDXOzdgRhWH3pLIWvAh0ImvAuBhDCGR/43nAcevOfoTEZa6OrU/YbUJIoowYdFFBB1wHSn6qL/fQcyMRrlbS7UXsA4gy6rPE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
